OBJS = ../../src/save.cpp main.c
CC = g++
COMPILER_FLAGS = -std=c++11
LINKER_FLAGS = 
OBJ_NAME = save_test

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

clean:
	rm -f $(OBJ_NAME)
