/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: map.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "map.pb-c.h"
void   square__init
                     (Square         *message)
{
  static Square init_value = SQUARE__INIT;
  *message = init_value;
}
size_t square__get_packed_size
                     (const Square *message)
{
  assert(message->base.descriptor == &square__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t square__pack
                     (const Square *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &square__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t square__pack_to_buffer
                     (const Square *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &square__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Square *
       square__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Square *)
     protobuf_c_message_unpack (&square__descriptor,
                                allocator, len, data);
}
void   square__free_unpacked
                     (Square *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &square__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chunk__init
                     (Chunk         *message)
{
  static Chunk init_value = CHUNK__INIT;
  *message = init_value;
}
size_t chunk__get_packed_size
                     (const Chunk *message)
{
  assert(message->base.descriptor == &chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chunk__pack
                     (const Chunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chunk__pack_to_buffer
                     (const Chunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Chunk *
       chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Chunk *)
     protobuf_c_message_unpack (&chunk__descriptor,
                                allocator, len, data);
}
void   chunk__free_unpacked
                     (Chunk *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   map__init
                     (Map         *message)
{
  static Map init_value = MAP__INIT;
  *message = init_value;
}
size_t map__get_packed_size
                     (const Map *message)
{
  assert(message->base.descriptor == &map__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t map__pack
                     (const Map *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &map__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t map__pack_to_buffer
                     (const Map *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &map__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Map *
       map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Map *)
     protobuf_c_message_unpack (&map__descriptor,
                                allocator, len, data);
}
void   map__free_unpacked
                     (Map *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &map__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor square__field_descriptors[4] =
{
  {
    "floor",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Square, floor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Square, item),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Square, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Square, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned square__field_indices_by_name[] = {
  0,   /* field[0] = floor */
  1,   /* field[1] = item */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange square__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor square__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "square",
  "Square",
  "Square",
  "",
  sizeof(Square),
  4,
  square__field_descriptors,
  square__field_indices_by_name,
  1,  square__number_ranges,
  (ProtobufCMessageInit) square__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chunk__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Chunk, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Chunk, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squares",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Chunk, n_squares),
    offsetof(Chunk, squares),
    &square__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chunk__field_indices_by_name[] = {
  2,   /* field[2] = squares */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chunk",
  "Chunk",
  "Chunk",
  "",
  sizeof(Chunk),
  3,
  chunk__field_descriptors,
  chunk__field_indices_by_name,
  1,  chunk__number_ranges,
  (ProtobufCMessageInit) chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor map__field_descriptors[1] =
{
  {
    "chunks",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Map, n_chunks),
    offsetof(Map, chunks),
    &chunk__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned map__field_indices_by_name[] = {
  0,   /* field[0] = chunks */
};
static const ProtobufCIntRange map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor map__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "map",
  "Map",
  "Map",
  "",
  sizeof(Map),
  1,
  map__field_descriptors,
  map__field_indices_by_name,
  1,  map__number_ranges,
  (ProtobufCMessageInit) map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
