/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: player-data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "player-data.pb-c.h"
void   player_data__init
                     (PlayerData         *message)
{
  static PlayerData init_value = PLAYER_DATA__INIT;
  *message = init_value;
}
size_t player_data__get_packed_size
                     (const PlayerData *message)
{
  assert(message->base.descriptor == &player_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_data__pack
                     (const PlayerData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_data__pack_to_buffer
                     (const PlayerData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerData *
       player_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerData *)
     protobuf_c_message_unpack (&player_data__descriptor,
                                allocator, len, data);
}
void   player_data__free_unpacked
                     (PlayerData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &player_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor player_data__field_descriptors[10] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PlayerData, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerData, health),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(PlayerData, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(PlayerData, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerData, velocity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inventory_item_id",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PlayerData, n_inventory_item_id),
    offsetof(PlayerData, inventory_item_id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inventory_number",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PlayerData, n_inventory_number),
    offsetof(PlayerData, inventory_number),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toolbar_item_id",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PlayerData, n_toolbar_item_id),
    offsetof(PlayerData, toolbar_item_id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toolbar_number",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PlayerData, n_toolbar_number),
    offsetof(PlayerData, toolbar_number),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "selected_tool",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerData, selected_tool),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_data__field_indices_by_name[] = {
  1,   /* field[1] = health */
  5,   /* field[5] = inventory_item_id */
  6,   /* field[6] = inventory_number */
  0,   /* field[0] = name */
  9,   /* field[9] = selected_tool */
  7,   /* field[7] = toolbar_item_id */
  8,   /* field[8] = toolbar_number */
  4,   /* field[4] = velocity */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange player_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor player_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "player_data",
  "PlayerData",
  "PlayerData",
  "",
  sizeof(PlayerData),
  10,
  player_data__field_descriptors,
  player_data__field_indices_by_name,
  1,  player_data__number_ranges,
  (ProtobufCMessageInit) player_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
