/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tile.pb-c.h"
void   square_proto__init
                     (SquareProto         *message)
{
  static SquareProto init_value = SQUARE_PROTO__INIT;
  *message = init_value;
}
size_t square_proto__get_packed_size
                     (const SquareProto *message)
{
  assert(message->base.descriptor == &square_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t square_proto__pack
                     (const SquareProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &square_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t square_proto__pack_to_buffer
                     (const SquareProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &square_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SquareProto *
       square_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SquareProto *)
     protobuf_c_message_unpack (&square_proto__descriptor,
                                allocator, len, data);
}
void   square_proto__free_unpacked
                     (SquareProto *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &square_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chunk_proto__init
                     (ChunkProto         *message)
{
  static ChunkProto init_value = CHUNK_PROTO__INIT;
  *message = init_value;
}
size_t chunk_proto__get_packed_size
                     (const ChunkProto *message)
{
  assert(message->base.descriptor == &chunk_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chunk_proto__pack
                     (const ChunkProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chunk_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chunk_proto__pack_to_buffer
                     (const ChunkProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chunk_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChunkProto *
       chunk_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChunkProto *)
     protobuf_c_message_unpack (&chunk_proto__descriptor,
                                allocator, len, data);
}
void   chunk_proto__free_unpacked
                     (ChunkProto *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &chunk_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tile_proto__init
                     (TileProto         *message)
{
  static TileProto init_value = TILE_PROTO__INIT;
  *message = init_value;
}
size_t tile_proto__get_packed_size
                     (const TileProto *message)
{
  assert(message->base.descriptor == &tile_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tile_proto__pack
                     (const TileProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tile_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tile_proto__pack_to_buffer
                     (const TileProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tile_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TileProto *
       tile_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TileProto *)
     protobuf_c_message_unpack (&tile_proto__descriptor,
                                allocator, len, data);
}
void   tile_proto__free_unpacked
                     (TileProto *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tile_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor square_proto__field_descriptors[5] =
{
  {
    "floor",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SquareProto, floor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SquareProto, item),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quantity",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SquareProto, quantity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SquareProto, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SquareProto, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned square_proto__field_indices_by_name[] = {
  0,   /* field[0] = floor */
  1,   /* field[1] = item */
  2,   /* field[2] = quantity */
  3,   /* field[3] = x */
  4,   /* field[4] = y */
};
static const ProtobufCIntRange square_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor square_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "square_proto",
  "SquareProto",
  "SquareProto",
  "",
  sizeof(SquareProto),
  5,
  square_proto__field_descriptors,
  square_proto__field_indices_by_name,
  1,  square_proto__number_ranges,
  (ProtobufCMessageInit) square_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chunk_proto__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChunkProto, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChunkProto, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squares",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChunkProto, n_squares),
    offsetof(ChunkProto, squares),
    &square_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chunk_proto__field_indices_by_name[] = {
  2,   /* field[2] = squares */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange chunk_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chunk_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chunk_proto",
  "ChunkProto",
  "ChunkProto",
  "",
  sizeof(ChunkProto),
  3,
  chunk_proto__field_descriptors,
  chunk_proto__field_indices_by_name,
  1,  chunk_proto__number_ranges,
  (ProtobufCMessageInit) chunk_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tile_proto__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TileProto, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TileProto, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunks",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TileProto, n_chunks),
    offsetof(TileProto, chunks),
    &chunk_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tile_proto__field_indices_by_name[] = {
  2,   /* field[2] = chunks */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange tile_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tile_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tile_proto",
  "TileProto",
  "TileProto",
  "",
  sizeof(TileProto),
  3,
  tile_proto__field_descriptors,
  tile_proto__field_indices_by_name,
  1,  tile_proto__number_ranges,
  (ProtobufCMessageInit) tile_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
